version: '3.8'

services:
  transmission:
    image: transmission
    container_name: transmission-container
    privileged: true

    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    ports:
      - "9091:9091/tcp"
      - "51413:51413/tcp"
      - "51413:51413/udp"
    tmpfs:
      - /tmp
    volumes:
      - /home/user/transmission/config:/transmission/config
      - /home/user/transmission/downloads:/transmission/downloads
      - /home/user/transmission/incomplete:/transmission/incomplete
    restart: on-failure