apiVersion: apps/v1
kind: Deployment 
metadata:
  name: wireguardtransmission
  labels:
    app: wt-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wt-app
  template:  
    metadata:
      labels: 
        app: wt-app
    spec:    
      containers:
        - name: wt-app
          image: teomarcdhio/wgtr:1
          imagePullPolicy: Always
          ports: 
            - containerPort: 9091
            - containerPort: 51413
          securityContext:
             capabilities:
               add:
                 - NET_ADMIN
          volumeMounts:
            # - name: dev-net-tun
            #   mountPath: /dev/net/tun 
            - name: wt-downloads
              mountPath: /transmission/downloads 
            - name: wt-config
              mountPath: /transmission/config # Path of the volume in the container 
            - name: wt-incomplete
              mountPath: /transmission/incomplete # Path of the volume in the container  
            - name: wg-config
              mountPath: /etc/wireguard/wg0.conf # Path of the volume in the container                                        
      volumes: 
        - name: wt-downloads
          persistentVolumeClaim:
            claimName: microk8s-hostpath-pv   
        - name: wt-config
          hostPath:
             path: /home/matteo/transmission/config # Path of the directory on the Host (node)
             type: DirectoryOrCreate # DirectoryOrCreate, FileOrCreate  
        - name: wt-incomplete
          hostPath:
             path: /home/matteo/transmission/incomplete # Path of the directory on the Host (node)
             type: DirectoryOrCreate # DirectoryOrCreate, FileOrCreate  
        - name: wg-config
          hostPath:
             path: /home/matteo/wg/wg0.conf # Path of the directory on the Host (node)
             type: FileOrCreate # DirectoryOrCreate, FileOrCreate
        # - name: dev-net-tun
        #   hostPath:
        #      path: /dev/net/tun # Path of the directory on the Host (node)
        #      type: FileOrCreate # DirectoryOrCreate, FileOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: microk8s-hostpath-pv
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: microk8s-hostpath ## Microk8s standard storage Class
  resources:
    requests:
      storage: 15Gi
---
apiVersion: v1
kind: Service 
metadata:
  name: wt-service
  labels:
    app: wt-service 
spec:
  type: LoadBalancer # ClusterIp, # NodePort
  selector:
    app: wt-app
  ports: 
    - name: tr
      port: 9091 # Service Port
      targetPort: 9091 # Container Port  
    - name: tr2
      port: 51413 # Service Port
      targetPort: 51413 # Container Port   